
CREATE TABLE datatable_json_jsonb (

  id varchar(40) PRIMARY KEY,
  displayType            varchar(100),
  sourceType         varchar(200),
  dataSize         bigint,
  dataConfig            json,
  chartIds              json,
  suggestChartIds            json,
  status   varchar(20),
  dbTableName  varchar(200),
  columns  json,
  revisions  json,
  enableAuth  boolean,
  asyncDataTable json,
  description varchar(300),
  appMetaDataProperties json,
  userId varchar(20),
  ownerId varchar(20),
  name varchar(200),
  version int,
  deleted int,
  accesses json,
  groupAccesses json,
  accessList jsonb,
  groupAccessList jsonb,
  tags json,
  copyFrom varchar(100),
  receiveFrom varchar(100),
  creatorId varchar(100),
  categoryId varchar(100)
);

CREATE TABLE datatable_json (
  id varchar(40) PRIMARY KEY,
  displayType            varchar(100),
  sourceType         varchar(200),
  dataSize         bigint,
  dataConfig            json,
  chartIds              json,
  suggestChartIds            json,
  status   varchar(20),
  dbTableName  varchar(200),
  columns  json,
  revisions  json,
  enableAuth  boolean,
  asyncDataTable json,
  description varchar(300),
  appMetaDataProperties json,
  userId varchar(20),
  ownerId varchar(20),
  name varchar(200),
  version int,
  deleted int,
  accesses json,
  groupAccesses json,
  accessList json,
  groupAccessList json,
  tags json,
  copyFrom varchar(100),
  receiveFrom varchar(100),
  creatorId varchar(100),
  categoryId varchar(100)
);

CREATE TABLE datatable_jsonb (
  id varchar(40) PRIMARY KEY,
  displayType            varchar(100),
  sourceType         varchar(200),
  dataSize         bigint,
  dataConfig            jsonb,
  chartIds              jsonb,
  suggestChartIds            jsonb,
  status   varchar(20),
  dbTableName  varchar(200),
  columns  jsonb,
  revisions  jsonb,
  enableAuth  boolean,
  asyncDataTable jsonb,
  description varchar(300),
  appMetaDataProperties jsonb,
  userId varchar(20),
  ownerId varchar(20),
  name varchar(200),
  version int,
  deleted int,
  accesses jsonb,
  groupAccesses jsonb,
  accessList jsonb,
  groupAccessList jsonb,
  tags jsonb,
  copyFrom varchar(100),
  receiveFrom varchar(100),
  creatorId varchar(100),
  categoryId varchar(100)
);